version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_tickets
    restart: always
    environment:
      # Estos datos deben ser IGUALES en tu DatabaseManager.java
      MYSQL_DATABASE: ticket_db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: